//go:build !ignore_autogenerated

// Hand-written deepcopy for KafkaCluster types. Mirrors what controller-gen would
// produce; kept separate from zz_generated.deepcopy.go so a future
// `make manifests` regeneration can overwrite the generated file safely.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *KafkaCluster) DeepCopyInto(out *KafkaCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *KafkaCluster) DeepCopy() *KafkaCluster {
	if in == nil {
		return nil
	}
	out := new(KafkaCluster)
	in.DeepCopyInto(out)
	return out
}

func (in *KafkaCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *KafkaClusterList) DeepCopyInto(out *KafkaClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		items := make([]KafkaCluster, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&items[i])
		}
		out.Items = items
	}
}

func (in *KafkaClusterList) DeepCopy() *KafkaClusterList {
	if in == nil {
		return nil
	}
	out := new(KafkaClusterList)
	in.DeepCopyInto(out)
	return out
}

func (in *KafkaClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *KafkaClusterSpec) DeepCopyInto(out *KafkaClusterSpec) {
	*out = *in
	out.Storage = in.Storage
	in.Listeners.DeepCopyInto(&out.Listeners)
}

func (in *KafkaClusterListeners) DeepCopyInto(out *KafkaClusterListeners) {
	out.Internal = in.Internal
	in.External.DeepCopyInto(&out.External)
}

func (in *KafkaClusterExternalListener) DeepCopyInto(out *KafkaClusterExternalListener) {
	*out = *in
	out.TLS = in.TLS
	out.Gateway = in.Gateway
	if in.Service.Annotations != nil {
		m := make(map[string]string, len(in.Service.Annotations))
		for k, v := range in.Service.Annotations {
			m[k] = v
		}
		out.Service.Annotations = m
	}
}

func (in *KafkaClusterStatus) DeepCopyInto(out *KafkaClusterStatus) {
	*out = *in
	if in.BootstrapServers != nil {
		out.BootstrapServers = append([]string(nil), in.BootstrapServers...)
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}
