//go:build !ignore_autogenerated

// Hand-written deepcopy for KafkaClusterAssignments types. Mirrors what
// controller-gen would produce; kept separate from zz_generated.deepcopy.go
// so a future `make manifests` regeneration can overwrite the generated file
// safely.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *KafkaClusterAssignments) DeepCopyInto(out *KafkaClusterAssignments) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *KafkaClusterAssignments) DeepCopy() *KafkaClusterAssignments {
	if in == nil {
		return nil
	}
	out := new(KafkaClusterAssignments)
	in.DeepCopyInto(out)
	return out
}

func (in *KafkaClusterAssignments) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *KafkaClusterAssignmentsList) DeepCopyInto(out *KafkaClusterAssignmentsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		items := make([]KafkaClusterAssignments, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&items[i])
		}
		out.Items = items
	}
}

func (in *KafkaClusterAssignmentsList) DeepCopy() *KafkaClusterAssignmentsList {
	if in == nil {
		return nil
	}
	out := new(KafkaClusterAssignmentsList)
	in.DeepCopyInto(out)
	return out
}

func (in *KafkaClusterAssignmentsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *KafkaClusterAssignmentsStatus) DeepCopyInto(out *KafkaClusterAssignmentsStatus) {
	*out = *in
	if in.Brokers != nil {
		out.Brokers = append([]KafkaClusterBroker(nil), in.Brokers...)
	}
	if in.Partitions != nil {
		out.Partitions = append([]KafkaClusterPartitionAssign(nil), in.Partitions...)
	}
	if in.ConsumerGroups != nil {
		out.ConsumerGroups = append([]KafkaClusterConsumerGroupAssign(nil), in.ConsumerGroups...)
	}
}
