// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: heartbeat.proto

// Package heartbeat is the v3 cluster-coordination protocol between brokers
// and the elected controller. Bidirectional gRPC: brokers stream BrokerStatus
// upstream every ~1s; the controller streams ControllerCommand back, sending
// PING for liveness and ASSIGNMENT_CHANGED to push assignment.json refreshes.
//
// Phase 4 wires the client/server. Phase 1 only ships this schema.

package heartbeatpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControllerHeartbeat_Stream_FullMethodName = "/skafka.heartbeat.v1.ControllerHeartbeat/Stream"
)

// ControllerHeartbeatClient is the client API for ControllerHeartbeat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControllerHeartbeatClient interface {
	// Stream is opened by the broker. Long-lived; reconnect on disconnect.
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BrokerStatus, ControllerCommand], error)
}

type controllerHeartbeatClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerHeartbeatClient(cc grpc.ClientConnInterface) ControllerHeartbeatClient {
	return &controllerHeartbeatClient{cc}
}

func (c *controllerHeartbeatClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BrokerStatus, ControllerCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControllerHeartbeat_ServiceDesc.Streams[0], ControllerHeartbeat_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BrokerStatus, ControllerCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControllerHeartbeat_StreamClient = grpc.BidiStreamingClient[BrokerStatus, ControllerCommand]

// ControllerHeartbeatServer is the server API for ControllerHeartbeat service.
// All implementations should embed UnimplementedControllerHeartbeatServer
// for forward compatibility.
type ControllerHeartbeatServer interface {
	// Stream is opened by the broker. Long-lived; reconnect on disconnect.
	Stream(grpc.BidiStreamingServer[BrokerStatus, ControllerCommand]) error
}

// UnimplementedControllerHeartbeatServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControllerHeartbeatServer struct{}

func (UnimplementedControllerHeartbeatServer) Stream(grpc.BidiStreamingServer[BrokerStatus, ControllerCommand]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedControllerHeartbeatServer) testEmbeddedByValue() {}

// UnsafeControllerHeartbeatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerHeartbeatServer will
// result in compilation errors.
type UnsafeControllerHeartbeatServer interface {
	mustEmbedUnimplementedControllerHeartbeatServer()
}

func RegisterControllerHeartbeatServer(s grpc.ServiceRegistrar, srv ControllerHeartbeatServer) {
	// If the following call panics, it indicates UnimplementedControllerHeartbeatServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControllerHeartbeat_ServiceDesc, srv)
}

func _ControllerHeartbeat_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControllerHeartbeatServer).Stream(&grpc.GenericServerStream[BrokerStatus, ControllerCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControllerHeartbeat_StreamServer = grpc.BidiStreamingServer[BrokerStatus, ControllerCommand]

// ControllerHeartbeat_ServiceDesc is the grpc.ServiceDesc for ControllerHeartbeat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControllerHeartbeat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "skafka.heartbeat.v1.ControllerHeartbeat",
	HandlerType: (*ControllerHeartbeatServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _ControllerHeartbeat_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "heartbeat.proto",
}
