// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: heartbeat.proto

// Package heartbeat is the v3 cluster-coordination protocol between brokers
// and the elected controller. Bidirectional gRPC: brokers stream BrokerStatus
// upstream every ~1s; the controller streams ControllerCommand back, sending
// PING for liveness and ASSIGNMENT_CHANGED to push assignment.json refreshes.
//
// Phase 4 wires the client/server. Phase 1 only ships this schema.

package heartbeatpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PartitionStatus_State int32

const (
	PartitionStatus_READY      PartitionStatus_State = 0
	PartitionStatus_RECOVERING PartitionStatus_State = 1
	PartitionStatus_ERROR      PartitionStatus_State = 2
)

// Enum value maps for PartitionStatus_State.
var (
	PartitionStatus_State_name = map[int32]string{
		0: "READY",
		1: "RECOVERING",
		2: "ERROR",
	}
	PartitionStatus_State_value = map[string]int32{
		"READY":      0,
		"RECOVERING": 1,
		"ERROR":      2,
	}
)

func (x PartitionStatus_State) Enum() *PartitionStatus_State {
	p := new(PartitionStatus_State)
	*p = x
	return p
}

func (x PartitionStatus_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PartitionStatus_State) Descriptor() protoreflect.EnumDescriptor {
	return file_heartbeat_proto_enumTypes[0].Descriptor()
}

func (PartitionStatus_State) Type() protoreflect.EnumType {
	return &file_heartbeat_proto_enumTypes[0]
}

func (x PartitionStatus_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PartitionStatus_State.Descriptor instead.
func (PartitionStatus_State) EnumDescriptor() ([]byte, []int) {
	return file_heartbeat_proto_rawDescGZIP(), []int{1, 0}
}

type ControllerCommand_Type int32

const (
	ControllerCommand_PING               ControllerCommand_Type = 0 // standard heartbeat, refresh broker liveness
	ControllerCommand_LEAVING            ControllerCommand_Type = 1 // controller shutting down gracefully
	ControllerCommand_ASSIGNMENT_CHANGED ControllerCommand_Type = 2 // re-read /data/__cluster/assignment.json now
)

// Enum value maps for ControllerCommand_Type.
var (
	ControllerCommand_Type_name = map[int32]string{
		0: "PING",
		1: "LEAVING",
		2: "ASSIGNMENT_CHANGED",
	}
	ControllerCommand_Type_value = map[string]int32{
		"PING":               0,
		"LEAVING":            1,
		"ASSIGNMENT_CHANGED": 2,
	}
)

func (x ControllerCommand_Type) Enum() *ControllerCommand_Type {
	p := new(ControllerCommand_Type)
	*p = x
	return p
}

func (x ControllerCommand_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControllerCommand_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_heartbeat_proto_enumTypes[1].Descriptor()
}

func (ControllerCommand_Type) Type() protoreflect.EnumType {
	return &file_heartbeat_proto_enumTypes[1]
}

func (x ControllerCommand_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControllerCommand_Type.Descriptor instead.
func (ControllerCommand_Type) EnumDescriptor() ([]byte, []int) {
	return file_heartbeat_proto_rawDescGZIP(), []int{2, 0}
}

// BrokerStatus is sent upstream from broker to controller every
// heartbeatIntervalMs (default 1000ms).
type BrokerStatus struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	BrokerId    string                 `protobuf:"bytes,1,opt,name=broker_id,json=brokerId,proto3" json:"broker_id,omitempty"`
	TimestampMs int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// Highest assignmentVersion the broker has applied. Lets the controller
	// detect brokers that missed an ASSIGNMENT_CHANGED push and re-deliver.
	LastSeenAssignmentVersion uint64             `protobuf:"varint,3,opt,name=last_seen_assignment_version,json=lastSeenAssignmentVersion,proto3" json:"last_seen_assignment_version,omitempty"`
	Partitions                []*PartitionStatus `protobuf:"bytes,4,rep,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *BrokerStatus) Reset() {
	*x = BrokerStatus{}
	mi := &file_heartbeat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerStatus) ProtoMessage() {}

func (x *BrokerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_heartbeat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerStatus.ProtoReflect.Descriptor instead.
func (*BrokerStatus) Descriptor() ([]byte, []int) {
	return file_heartbeat_proto_rawDescGZIP(), []int{0}
}

func (x *BrokerStatus) GetBrokerId() string {
	if x != nil {
		return x.BrokerId
	}
	return ""
}

func (x *BrokerStatus) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *BrokerStatus) GetLastSeenAssignmentVersion() uint64 {
	if x != nil {
		return x.LastSeenAssignmentVersion
	}
	return 0
}

func (x *BrokerStatus) GetPartitions() []*PartitionStatus {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type PartitionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     int32                  `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	Epoch         uint32                 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	State         PartitionStatus_State  `protobuf:"varint,4,opt,name=state,proto3,enum=skafka.heartbeat.v1.PartitionStatus_State" json:"state,omitempty"`
	HighWatermark int64                  `protobuf:"varint,5,opt,name=high_watermark,json=highWatermark,proto3" json:"high_watermark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionStatus) Reset() {
	*x = PartitionStatus{}
	mi := &file_heartbeat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionStatus) ProtoMessage() {}

func (x *PartitionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_heartbeat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionStatus.ProtoReflect.Descriptor instead.
func (*PartitionStatus) Descriptor() ([]byte, []int) {
	return file_heartbeat_proto_rawDescGZIP(), []int{1}
}

func (x *PartitionStatus) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PartitionStatus) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *PartitionStatus) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *PartitionStatus) GetState() PartitionStatus_State {
	if x != nil {
		return x.State
	}
	return PartitionStatus_READY
}

func (x *PartitionStatus) GetHighWatermark() int64 {
	if x != nil {
		return x.HighWatermark
	}
	return 0
}

// ControllerCommand is pushed downstream from controller to broker.
type ControllerCommand struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Type        ControllerCommand_Type `protobuf:"varint,2,opt,name=type,proto3,enum=skafka.heartbeat.v1.ControllerCommand_Type" json:"type,omitempty"`
	// Populated when type == ASSIGNMENT_CHANGED.
	AssignmentVersion uint64 `protobuf:"varint,3,opt,name=assignment_version,json=assignmentVersion,proto3" json:"assignment_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ControllerCommand) Reset() {
	*x = ControllerCommand{}
	mi := &file_heartbeat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerCommand) ProtoMessage() {}

func (x *ControllerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_heartbeat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerCommand.ProtoReflect.Descriptor instead.
func (*ControllerCommand) Descriptor() ([]byte, []int) {
	return file_heartbeat_proto_rawDescGZIP(), []int{2}
}

func (x *ControllerCommand) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *ControllerCommand) GetType() ControllerCommand_Type {
	if x != nil {
		return x.Type
	}
	return ControllerCommand_PING
}

func (x *ControllerCommand) GetAssignmentVersion() uint64 {
	if x != nil {
		return x.AssignmentVersion
	}
	return 0
}

var File_heartbeat_proto protoreflect.FileDescriptor

const file_heartbeat_proto_rawDesc = "" +
	"\n" +
	"\x0fheartbeat.proto\x12\x13skafka.heartbeat.v1\"\xd5\x01\n" +
	"\fBrokerStatus\x12\x1b\n" +
	"\tbroker_id\x18\x01 \x01(\tR\bbrokerId\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12?\n" +
	"\x1clast_seen_assignment_version\x18\x03 \x01(\x04R\x19lastSeenAssignmentVersion\x12D\n" +
	"\n" +
	"partitions\x18\x04 \x03(\v2$.skafka.heartbeat.v1.PartitionStatusR\n" +
	"partitions\"\xf3\x01\n" +
	"\x0fPartitionStatus\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\x05R\tpartition\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\rR\x05epoch\x12@\n" +
	"\x05state\x18\x04 \x01(\x0e2*.skafka.heartbeat.v1.PartitionStatus.StateR\x05state\x12%\n" +
	"\x0ehigh_watermark\x18\x05 \x01(\x03R\rhighWatermark\"-\n" +
	"\x05State\x12\t\n" +
	"\x05READY\x10\x00\x12\x0e\n" +
	"\n" +
	"RECOVERING\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x02\"\xdd\x01\n" +
	"\x11ControllerCommand\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x12?\n" +
	"\x04type\x18\x02 \x01(\x0e2+.skafka.heartbeat.v1.ControllerCommand.TypeR\x04type\x12-\n" +
	"\x12assignment_version\x18\x03 \x01(\x04R\x11assignmentVersion\"5\n" +
	"\x04Type\x12\b\n" +
	"\x04PING\x10\x00\x12\v\n" +
	"\aLEAVING\x10\x01\x12\x16\n" +
	"\x12ASSIGNMENT_CHANGED\x10\x022n\n" +
	"\x13ControllerHeartbeat\x12W\n" +
	"\x06Stream\x12!.skafka.heartbeat.v1.BrokerStatus\x1a&.skafka.heartbeat.v1.ControllerCommand(\x010\x01B\xd3\x01\n" +
	"\x17com.skafka.heartbeat.v1B\x0eHeartbeatProtoP\x01Z:github.com/woestebanaan/skafka/pkg/heartbeatpb;heartbeatpb\xa2\x02\x03SHX\xaa\x02\x13Skafka.Heartbeat.V1\xca\x02\x13Skafka\\Heartbeat\\V1\xe2\x02\x1fSkafka\\Heartbeat\\V1\\GPBMetadata\xea\x02\x15Skafka::Heartbeat::V1b\x06proto3"

var (
	file_heartbeat_proto_rawDescOnce sync.Once
	file_heartbeat_proto_rawDescData []byte
)

func file_heartbeat_proto_rawDescGZIP() []byte {
	file_heartbeat_proto_rawDescOnce.Do(func() {
		file_heartbeat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_heartbeat_proto_rawDesc), len(file_heartbeat_proto_rawDesc)))
	})
	return file_heartbeat_proto_rawDescData
}

var file_heartbeat_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_heartbeat_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_heartbeat_proto_goTypes = []any{
	(PartitionStatus_State)(0),  // 0: skafka.heartbeat.v1.PartitionStatus.State
	(ControllerCommand_Type)(0), // 1: skafka.heartbeat.v1.ControllerCommand.Type
	(*BrokerStatus)(nil),        // 2: skafka.heartbeat.v1.BrokerStatus
	(*PartitionStatus)(nil),     // 3: skafka.heartbeat.v1.PartitionStatus
	(*ControllerCommand)(nil),   // 4: skafka.heartbeat.v1.ControllerCommand
}
var file_heartbeat_proto_depIdxs = []int32{
	3, // 0: skafka.heartbeat.v1.BrokerStatus.partitions:type_name -> skafka.heartbeat.v1.PartitionStatus
	0, // 1: skafka.heartbeat.v1.PartitionStatus.state:type_name -> skafka.heartbeat.v1.PartitionStatus.State
	1, // 2: skafka.heartbeat.v1.ControllerCommand.type:type_name -> skafka.heartbeat.v1.ControllerCommand.Type
	2, // 3: skafka.heartbeat.v1.ControllerHeartbeat.Stream:input_type -> skafka.heartbeat.v1.BrokerStatus
	4, // 4: skafka.heartbeat.v1.ControllerHeartbeat.Stream:output_type -> skafka.heartbeat.v1.ControllerCommand
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_heartbeat_proto_init() }
func file_heartbeat_proto_init() {
	if File_heartbeat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_heartbeat_proto_rawDesc), len(file_heartbeat_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_heartbeat_proto_goTypes,
		DependencyIndexes: file_heartbeat_proto_depIdxs,
		EnumInfos:         file_heartbeat_proto_enumTypes,
		MessageInfos:      file_heartbeat_proto_msgTypes,
	}.Build()
	File_heartbeat_proto = out.File
	file_heartbeat_proto_goTypes = nil
	file_heartbeat_proto_depIdxs = nil
}
